# Generated by Django 5.1.7 on 2025-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], default='individual', max_length=20),
        ),
    ]
