# Generated by Django 5.1.7 on 2025-05-12 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_competition_category_competition_close_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Business', 'Business'), ('Art', 'Art & Design'), ('Science', 'Science'), ('other', 'Other')], default='Technology', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='close_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 5, 44, 44, 317964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Team', 'Team')], default='Individual', max_length=20),
        ),
    ]
