# Generated by Django 5.1.7 on 2025-08-03 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_userprofile_age_userprofile_field_of_study_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="close_registration",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 10, 15, 18, 7, 611678, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
