# Generated by Django 5.1.7 on 2025-08-06 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_competition_close_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='close_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 11, 13, 49, 480175, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='CompetitionRegistration',
        ),
    ]
