# Generated by Django 5.1.7 on 2025-08-03 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_competition_close_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="close_registration",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 10, 15, 39, 23, 926758, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
