# Generated by Django 5.1.7 on 2025-08-05 23:38

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_competition_close_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="competition",
            name="close_registration",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 12, 23, 38, 46, 627457, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
